### ISSUE TITLE
linux: running make doesn't find exec/types.h ?

### ISSUE THREAD

**Issue by alexmyczko** [pete-gordon/hivelytracker#15]
$ make
gcc -c ht.c -o ht.o -Wall -O3 -gstabs -I.
ht.c:8:10: fatal error: exec/types.h: No such file or directory
 #include <exec/types.h>
          ^~~~~~~~~~~~~~
compilation terminated.
makefile:16: recipe for target 'ht.o' failed
make: *** [ht.o] Error 1

what could i be missing?

**Comment by pete-gordon** [comment]
The top-level makefile is the original Amiga makefile.

You need to change into the sdl directory and use "make -f Makefile.linux"

**Comment by alexmyczko** [comment]
Thanks that helped!
