### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by alexmyczko** [pete-gordon/hivelytracker#16]
hi pete, what license would this source code be distributed with?

**Comment by alexmyczko** [comment]
just found the vintage skin theme :) lovely. and it loads and plays my huge AHX collection. once a free software license is assigned, be assured, this will get packaged into Debian and Ubuntu...

**Comment by pete-gordon** [comment]
The license issue is tricky. Hively was based on the WinAHX replayer by Abyss, but that never had a defined licence. I think when this was hosted on google code, I selected BSD license, and nobody complained, so lets say BSD license ;-)

**Comment by alexmyczko** [comment]
sounds good. What about putting a reald LICENSE file there? to make it more official?

**Comment by alexmyczko** [comment]
which one of them? https://en.wikipedia.org/wiki/BSD_licenses
