### ISSUE TITLE
gtk2 to gtk3 migration (or maybe get rid of it completely)?

### ISSUE THREAD

**Issue by alexmyczko** [pete-gordon/hivelytracker#17]
there's not much gtk code when searching like this

https://github.com/pete-gordon/hivelytracker/search?utf8=%E2%9C%93&q=gtk&type=

and gtk2 is quite old, and will be obsolete/removed sometime...

**Comment by pete-gordon** [comment]
Nobody is maintaining the linux port (that I'm aware of). I cobbled together the current Linux build but stopped working on it immediately ;-)

I welcome any pull requests :-D

**Comment by alexmyczko** [comment]
sounds fair... ;)

**Comment by SamuraiCrow** [comment]
I would get rid of the native requesters if it can be replaced with something cross platform.  Maybe something SDL based.  That will aid in unifying the code base.

**Comment by akhilman** [comment]
File dialogs for linux could be replaced by [FileChooser Portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser). Portal provides native for desktop environment file chooser dialog.

**Comment by mywave82** [comment]
https://github.com/mlabbe/nativefiledialog

Looks like a possible OK solution. But if only Gtk2 on Linux is the only one currently not being up-to-date, then it might be easier to just fix that one I guess.
