### ISSUE TITLE
AHX playback results in very bad noise near ending

### ISSUE THREAD

**Issue by bryc** [pete-gordon/hivelytracker#40]
The AHX file in question: https://modland.ziphoid.com/pub/modules/AHX/Yelm/oldskoolcrackintrosong.ahx

It plays for about a minute, then on the last pattern, there is a slight pause before a final deep decaying chord/crescendo, which plays seemingly infinitely (speed is set to `F00`). It sounds correct on AHX under Amiga, however, HivelyTracker outputs a loud buzz sound instead. This bug carries over to the XMPlay plugin as well, where it's held for an additional 1 minute of play time before moving to the next track. Foobar2000 solves this issue by skipping the infinite ending altogether (but not relevant to hively itself).

It appears to be some AHX quirk, because something similar occurs in bartman/abyss's JS player.

**Comment by pachuco** [comment]
What I've gathered so far from this is that when speed is set to 0 and there are notes on the same row, the replayer keeps trying to retrigger note on each tick.

**Comment by bryc** [comment]
@pachuco Nice, that seems to fix the issue (at least in my JS AHX player). 

I'm not knowledgable to say if it breaks anything (my uneducated guess is that it doesn't).

Does the change affect _all_ rows with `F00`, or _only_ the rows with `F00` that have non-zero Note/Instrument data?
 If the second, it narrows down the testing to only 7 files:

- **Yelm - Oldskoolcrackintrosong**
- **Varthall - this creamy nation**
- **Miao - logo**
- **Syphus - last tense** (Note: occurs in unused pattern 9)
- **Jazz (NL) - jingles** (Note: occurs beyond end point)
- **Jazz (NL) - hawaii-balls** (Note: occurs beyond end point)
- **Mermaid - kingkong** (Note: occurs beyond end point)

**Comment by pachuco** [comment]
Well, row data after the row that did F00 is not gonna matter, because it never gets reached.

Upon reaching such row, that branch of hvl_play_irq() would get endlessly retriggered on each tick/IRQ. The branch itself calls hvl_process_step() for each voice.

**Comment by pachuco** [comment]
Done differently in commit. Coincides with AHX.
