### ISSUE TITLE
More release tags?

### ISSUE THREAD

**Issue by mxmilkiib** [pete-gordon/hivelytracker#45]
Hi, I'd have added Hively Tracker to https://libreav.org/software but might I suggest that more release tags are made (with changelog message info) so that more of the recent updates can be broadcast? Thanks!

**Comment by pulkomandy** [comment]
There have been only some minor bugfixes since the last release in 2015, unless I'm missing something. Is it worth a new release?

**Comment by pachuco** [comment]
There've been replayer fixes recently. I think it's worth new release just for those alone.
Might want to squeeze in a few more before release, though.

**Comment by fgaz** [comment]
Bump! It'd be nice use an actual release in NixOS, instead of a commit sha:

https://github.com/NixOS/nixpkgs/blob/f5bd5bb0c95dda2f9e7e6d325705da1748bf65df/pkgs/applications/audio/hivelytracker/default.nix#L15-L20

**Comment by pete-gordon** [comment]
V1.9 was just tagged and released.

**Comment by fgaz** [comment]
Thank you!
