### ISSUE TITLE
HivelyTracker won't compile on Linux

### ISSUE THREAD

**Issue by kamkamkamkamkamkamkamkam** [pete-gordon/hivelytracker#47]
I've been trying to compile HivelyTracker on Linux because the builds on the website are too out of date and isn't compatible with newer versions of shared libraries anymore. (I can't run it because it's asking for an older version of libsdl-image) When I try to compile, it complains about missing files, the first one I was able to find in a different server and I edited ht.c to point in the right direction but when I try to compile after that it tells me this 
`ht.c:10:10: fatal error: proto/intuition.h: No such file or directory
`
I can't find this file anywhere in the source code, is there something I'm missing?

**Comment by pulkomandy** [comment]
intuition.h is specific to AmigaOS. The makefile at the root of the project is scecific to AmigaOS (Hively Trakcer original platform) and won't work for other systems. To build the Linux version you need to do:

    cd sdl
    make -f Makefile.linux
