### ISSUE TITLE
ECx effect crash the app

### ISSUE THREAD

**Issue by Speedvicio** [pete-gordon/hivelytracker#53]
I'm using hively 1.9 on win7 32bit , during playing, the effect ECx cause the crash of program.

**Comment by pete-gordon** [comment]
Can you attach an example file? ECx is working fine for me here on Windows 8 64bit, which is the nearest config I can test with to yours.

**Comment by Speedvicio** [comment]
The tune is not finished, but you can use it for test.
[target renegade_.zip](https://github.com/pete-gordon/hivelytracker/files/9896992/target.renegade_.zip)

**Comment by pachuco** [comment]
https://github.com/8bitbubsy/ahx2play/commit/31bbb8ecf6337a0a560fd37d53ba5b0877c16550
